export const CONTRACT_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_tenant", type: "address" },
      { internalType: "uint256", name: "_rentAmount", type: "uint256" },
      { internalType: "uint256", name: "_securityDeposit", type: "uint256" },
      { internalType: "uint256", name: "_startDate", type: "uint256" },
      { internalType: "uint256", name: "_endDate", type: "uint256" },
      { internalType: "uint256", name: "_gracePeriod", type: "uint256" },
    ],
    name: "createAgreement",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agreementId", type: "uint256" }],
    name: "acceptAgreement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agreementId", type: "uint256" }],
    name: "payRent",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agreementId", type: "uint256" }],
    name: "raiseDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "agreementId", type: "uint256" },
      { internalType: "bool", name: "tenantFavored", type: "bool" },
    ],
    name: "resolveDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agreementId", type: "uint256" }],
    name: "refundDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agreementId", type: "uint256" }],
    name: "terminateAgreement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agreementId", type: "uint256" }],
    name: "getAgreement",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "landlord", type: "address" },
      { internalType: "address", name: "tenant", type: "address" },
      { internalType: "uint256", name: "rentAmount", type: "uint256" },
      { internalType: "uint256", name: "securityDeposit", type: "uint256" },
      { internalType: "uint256", name: "startDate", type: "uint256" },
      { internalType: "uint256", name: "endDate", type: "uint256" },
      { internalType: "uint256", name: "gracePeriod", type: "uint256" },
      { internalType: "uint8", name: "state", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "paymentId", type: "uint256" }],
    name: "getPayment",
    outputs: [
      { internalType: "uint256", name: "agreementId", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "dueDate", type: "uint256" },
      { internalType: "uint256", name: "paidDate", type: "uint256" },
      { internalType: "uint8", name: "status", type: "uint8" },
      { internalType: "address", name: "payer", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agreementId", type: "uint256" }],
    name: "getAgreementPayments",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "landlord", type: "address" }],
    name: "getLandlordAgreements",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "tenant", type: "address" }],
    name: "getTenantAgreements",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "agreementId", type: "uint256" }],
    name: "agreementExists",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentTimestamp",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      { indexed: true, internalType: "address", name: "landlord", type: "address" },
      { indexed: true, internalType: "address", name: "tenant", type: "address" },
      { indexed: false, internalType: "uint256", name: "rentAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "securityDeposit", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "startDate", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "endDate", type: "uint256" },
    ],
    name: "AgreementCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint256", name: "id", type: "uint256" }],
    name: "AgreementActivated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "agreementId", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "paymentId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "address", name: "payer", type: "address" },
    ],
    name: "RentPaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "agreementId", type: "uint256" },
      { indexed: true, internalType: "address", name: "tenant", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "DepositRefunded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "agreementId", type: "uint256" },
      { indexed: true, internalType: "address", name: "raisedBy", type: "address" },
    ],
    name: "DisputeRaised",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "agreementId", type: "uint256" },
      { indexed: false, internalType: "bool", name: "tenantFavored", type: "bool" },
    ],
    name: "DisputeResolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint256", name: "agreementId", type: "uint256" }],
    name: "AgreementTerminated",
    type: "event",
  },
];

export const AGREEMENT_STATES = ["Pending", "Active", "Terminated", "Disputed", "Completed"];
export const PAYMENT_STATUSES = ["Unpaid", "Paid", "Overdue"];
